server:
  port: 4444
spring:
  application:
    name: API-GATEWAY
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
    
zuul:  prefix: /api
  routes:    priceservice:
           path: /price/**
           service-id: STOCK-PRICE-SERVICE
    calculationservice:
           path: /calculation/**
           service-id: STOCK-CALCULATION-SERVICE 
    uinservice:
           path: /ui/**
           service-id: STOCK-UI-SERVICE
                 